### PR TITLE
Replace `fake-k8s.sh` with `kwokctl` in e2e-test

### LINKED ISSUE #295: Replace `fake-k8s.sh` with `kwokctl` in e2e-test
### What would you like to be added?

Do this when `kwokctl` is ready

/kind feature
/assign

### Why is this needed?

fake-k8s has contributed to [k-sigs/kwok](https://github.com/kubernetes-sigs/kwok)

### PR DESCRIPTION
**Pull request by wzshiming**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

https://github.com/kubernetes-sigs/kwok

**Which issue(s) this PR fixes**:
Fixes #295

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by pacoxu — APPROVED** [review]
/lgtm

**Comment by Iceber** [comment]
/lgtm

@wzshiming Could we merge it now?

**Pull request merged**
