### PR TITLE
add contributing.md and code_of_conduct.md

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>
fix: https://github.com/clusterpedia-io/clusterpedia/issues/9#event-5712752698

### CODE REVIEW

**Comment by kerthcet** [comment]
lowercase clusterpedia and squash the commits already. @Iceber

**Comment by Iceber** [comment]
@kerthcet  Thank you very much for your contribution, it is a very important pr🎉.

**Pull request merged**
