### PR TITLE
Fix the permission of bot and merge jobs into one

### PR DESCRIPTION
**Pull request by wzshiming**
**What type of PR is this?**

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wzshiming** [comment]
`clusterpedia-io/gh-ci-bot` need to sync again

**Comment by Iceber** [comment]
Verified on https://github.com/DaoCloud-OpenSource/ci-bot-playground/pull/34, LGTM

**Comment by Iceber** [comment]
> `clusterpedia-io/gh-ci-bot` need to sync again

synced

**Pull request merged**
