### PR TITLE
add synced state to resource

### PR DESCRIPTION
**Pull request by calvin0327**
If the respurce had be synced by synchronizer， we should add a state  `Synced` to mark current state.

### CODE REVIEW

**Comment by calvin0327** [comment]
@Iceber PTAL

**Comment by Iceber** [comment]
I think there are three types of sync statuses:
* [`init synced`] first sync completed
* [`syncing`] resource event received and processing started
* [`synced`] the current resource queue emptied

Normally, the resource state should switch between `synced` and `syncing`.

@calvin0327 This is the idea for me, what do you think?

**Comment by calvin0327** [comment]
@Iceber I agree with that the resource state should switch between synced and syncing.  It's not necessary to add `init synced`  state, we can ues the `synced` replace it.

**Comment by calvin0327** [comment]
@Iceber /cc

**Review by Iceber — APPROVED** [review]
LGTM

**Pull request closed without merging**
