### PR TITLE
unify feature gate in aa、sync-controller and cluster-controller

### PR DESCRIPTION
**Pull request by wuyingjun-lucky**
Signed-off-by: wuyingjun <wuyingjun_yewu@cmss.chinamobile.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
unify default feature gate in aa、sync-controller and cluster-controller
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Iceber** [comment]
The reason for separating `clustersynchro manager`'s feature gate from `clusterpedia apiserver`'s is that apiserver's doesn't make any sense for `clustersynchro manager`, so a separate feature gate is used for clustersynchro manager in order to get a better view of the useful feature-gate

**Comment by wuyingjun-lucky** [comment]
> The reason for separating `clustersynchro manager`'s feature gate from `clusterpedia apiserver`'s is that apiserver's feature gates doesn't make any sense for `clustersynchro manager`, so a separate feature gate is used for clustersynchro manager in order to get a better view of the useful feature-gate

I am lack of knowledge here.  What I am confused about is two points：
1· cluster controller use the same feature-gates as sync controller 
2. AA and sync-controller start in two containers . Does that make have an effect when we do not separate the feature_gates
Can you help me?

**Comment by Iceber** [comment]
> 1. cluster controller use the same feature-gates as sync controller

They just use the same utils/feature package, which is actually empty if we don't import the specific features package.

[utils/feature](https://github.com/clusterpedia-io/clusterpedia/tree/main/pkg/utils/feature) can be used as a public feature gate for clusterpedia, and that components will register its own features if it needs to use them.


> 2. AA and sync-controller start in two containers . Does that has an effect when we do not separate the feature_gates

Indeed, if the command is integrated, both feature gates will be used.

There are two ways to do this, which are 
* Register all features in DefaultMutableFeatureGate, but for the other two components, there is no way to see the really useful feature gate with --help

* Add a `SetMutableFeatureGate` function in *utils/features* to override MutableFeatureGate in *utils/features*, and add an `AddFeatureGates` function in *pkg/synchromanager/features*, like [logs.AddFeatureGates](https://github.com/clusterpedia-io/clusterpedia/blob/main/cmd/clustersynchro-manager/app/synchro.go#L28)

**Pull request closed without merging**
