### PR TITLE
:seedling: added tests for controller package

### PR DESCRIPTION
**Pull request by khareyash05**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
To increase test coverage for `pkg/controller`

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
Note - Working on other files for the controller package

### CODE REVIEW

**Comment by khareyash05** [comment]
@Iceber I was actually confused. I can add more files to this PR if you want. Are there any specific files or maybe directories?

**Comment by Iceber** [comment]
lgtm, thanks for your contribution

**Comment by Iceber** [comment]
> Are there any specific files or maybe directories?

If you are interested, could you add some complex tests for the [clusterimportpolicy](https://github.com/clusterpedia-io/clusterpedia/tree/main/pkg/controller/clusterimportpolicy) and [pediaclusterlifecycle](https://github.com/clusterpedia-io/clusterpedia/tree/main/pkg/controller/pediaclusterlifecycle), such as https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/deployment_controller_test.go

**Review by Iceber — APPROVED** [review]

**Comment by khareyash05** [comment]
> > Are there any specific files or maybe directories?
> 
> If you are interested, could you add some complex tests for the [clusterimportpolicy](https://github.com/clusterpedia-io/clusterpedia/tree/main/pkg/controller/clusterimportpolicy) and [pediaclusterlifecycle](https://github.com/clusterpedia-io/clusterpedia/tree/main/pkg/controller/pediaclusterlifecycle), such as https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/deployment_controller_test.go

Will do that. Thanks

**Pull request merged**
