### PR TITLE
Bump go.uber.org/atomic from 1.7.0 to 1.10.0

### PR DESCRIPTION
**Pull request by scydas**
Signed-off-by: scydas <scyda@outlook.com>

**What type of PR is this?**
/label dependencies
/kind cleanup
**What this PR does / why we need it**:
related pr: https://github.com/clusterpedia-io/clusterpedia/pull/361
**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
```

### CODE REVIEW

**Comment by Iceber** [comment]
@wzshiming Hi, scydas is a member, but he does not support executing the label command
> You do not support using command label
https://github.com/clusterpedia-io/clusterpedia/pull/364#issuecomment-1247651539

**Comment by wzshiming** [comment]
@Iceber
`/label` Need Reviewer status, we move the plugin to Member status?
https://github.com/clusterpedia-io/clusterpedia/blob/99d1631bca84b5680012786cba1d4e36428d1d1d/.github/workflows/bot.yml#L44

**Comment by Iceber** [comment]
@wzshiming Sorry, I didn't notice, I got confused between label and label-kind. It looks like you can give the author,what do you think?

**Comment by wzshiming** [comment]
@Iceber NVM, I have a question, why not use `/kind dependency` for a more consistent style?

**Pull request merged**
