### PR TITLE
add go version minimum requirement detection

### PR DESCRIPTION
**Pull request by ONE7live**
Signed-off-by: ONE7live <wangqi_yewu@cmss.chinamobile.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
I had a problem when I started clusterpedia with a lower version of go, so I would like to suggest setting a minimum go version and check before starting.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Iceber** [comment]
The actual minimum version of clusterpedia is 1.17, the minimum version in the go mod is not updated, this is a new issue, you can fix it here or submit a new pr

> Caused by https://github.com/kubernetes-sigs/controller-runtime/blob/v0.12.1

**Comment by ONE7live** [comment]
@Iceber Done, the minimum check version has been modified to 1.17

**Comment by Iceber** [comment]
@ONE7live It seems that the go version check can be ensured by directly modifying the version in the go mod.
https://github.com/clusterpedia-io/clusterpedia/blob/478e2208efdeef96f69ca024392ad85f456b166f/go.mod#L1-L4

to
```
go 1.17
```

What do you think?

**Comment by ONE7live** [comment]
@Iceber It may not be completely. In my personal opinion, we can indeed use go mod to ensure the go version used by clusterpedia, but we cannot guarantee that the go version of the user's environment matches it. For example, when the user executes update-vendor.sh to download dependencies, it may be more friendly to perform some environmental checks in advance and give prompts than to directly download and then generate errors,  what do you think?

**Comment by Iceber** [comment]
I'm using go 1.17, I changed go mod to 1.18 and running go mod vendor gives me an error
```bash
$ make vendor
./hack/update-vendor.sh
running 'go mod tidy'
go mod tidy: go.mod file indicates go 1.18, but maximum supported version is 1.17
make: *** [vendor] Error 1
```
Does this do the same thing as the script?

**Comment by ONE7live** [comment]
It can be understood that the purpose is the same, just a few more tips.
image
The script is compared against the go version of the user's environment through a predefined minimum version.

**Comment by Iceber** [comment]
I think it might be better to restrict it in the go mod, so that maintenance costs can be reduced and the minimum version of go will need to be modified in one place in the future.

**Comment by ONE7live** [comment]
@Iceber Ok, thanks for your reply, I agree with you. Do you need me to close this PR?

**Comment by Iceber** [comment]
@ONE7live Although we use go mod to set the minimum version of go, the current minimum version in go.mod is wrong and should be 1.17. 

Would you like to submit pr to fix it?

**Pull request closed without merging**
