### PR TITLE
the exact chart dependecy version

### PR DESCRIPTION
**Pull request by calvin0327**
Signed-off-by: calvin0327 <wen.chen@daocloud.io>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
the chart version updates are very fast, We have not do any testing on the new version, so we should specify the  exact version.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Iceber** [comment]
https://github.com/clusterpedia-io/clusterpedia/runs/7849779721?check_suite_focus=true#step:4:1856

dependencies error:
```
  Error: the lock file (Chart.lock) is out of sync with the dependencies file (Chart.yaml). Please update the dependencies
  Error: INSTALLATION FAILED: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: postgresql, mysql, common
```

**Comment by calvin0327** [comment]
agree with you, so i will close the pr.

**Pull request closed without merging**
